name: test
on:
  push:
    branches:
      - v2-wip

jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest']
        go: [ '1.15', '1.16' ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}/${{ matrix.go }}
    steps:
      - uses: actions/checkout@master
      - name: Setup go ${{ matrix.go }}
        uses: actions/setup-go@master
        with:
          go-version: ${{ matrix.go }}
      - run: go test ./...
